apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-web
  namespace: argocd
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - shuailli.online
      secretName: ingress-tls-secret
  rules:
    - host: shuailli.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
