apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server

spec:
  template:
    spec:
      containers:
        - name: argocd-server
          args:
            - /usr/local/bin/argocd-server
            - --insecure # Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#kubernetesingress-nginx
            - --basehref #Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#ui-base-path
            - /argocd
