apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-applicationset-controller

$patch: delete
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-applicationset-controller

$patch: delete
