apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-notifications-controller

$patch: delete
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-notifications-controller-metrics

$patch: delete
