# 容器安全加固
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  template:
    spec:
      containers:
        - name: controller
          securityContext:
            readOnlyRootFilesystem: true

---

# DDoS 防护
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx

data:
  limit-req-zone: "$binary_remote_addr zone=reqlimit:10m rate=10r/s"
  limit_conn_zone: "$binary_remote_addr zone=conn_per_ip:64k"
  limit-req: "zone=reqlimit burst=20 nodelay"
  client-header-timeout: "10s"
  client-body-timeout: "5s"
  keepalive_timeout: "10s"
  use-forwarded-headers: "true"
  compute-full-forwarded-for: "true"

---

# SQL 注入防护
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx

data:
  enable-modsecurity: "true"
  enable-owasp-core-rules: "true"
  modsecurity-snippet: |-
    SecRuleEngine On
    SecAuditEngine RelevantOnly
    SecAuditLog /var/log/nginx/modsec_audit.log

    # === 引入规则 ===
    Include /etc/nginx/owasp-modsecurity-crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf

