apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      serviceAccountName: github-runner-sa
      containers:
        - name: github-runner
          image: myoung34/github-runner:latest
          env:
            - name: REPO_URL
              value: "https://github.com/bloom-mall/mall-migration"
            - name: LABELS
              value: "flyway-runner"
            - name: RUNNER_EPHEMERAL
              value: "true"
            - name: RUNNER_DISABLE_UPDATE
              value: "true"
            - name: DISABLE_RUNNER_UPDATE
              value: "true"
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-access-token
                  key: token
            # flyway运行时读取以下变量
            - name: FLYWAY_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-flyway-mall-rw-user
                  key: url
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-flyway-mall-rw-user
                  key: username
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-flyway-mall-rw-user
                  key: password
                  # resources:
                  #   limits:
                  #     cpu: "1"
                  #     memory: "512Mi"
                  #   requests:
                  #     cpu: "100m"
                  #     memory: "128Mi"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-runner-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-runner-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-runner-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-runner-role
subjects:
  - kind: ServiceAccount
    name: github-runner-sa
