apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tls-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: lishuaidev@126.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - selector: {}
        http01: # 使用80端口挑战，防火墙必须允许80端口
          ingress:
            ingressClassName: nginx
