apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tls-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: lishuaidev@126.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - selector: {}
        tlsALPN01: # 使用443端口挑战，因为80端口已关闭
          ingress:
            ingressClassName: nginx
