apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-gateway
  template:
    metadata:
      labels:
        app: mall-gateway
    spec:
      containers:
        - name: mall-gateway
          image: lishuaidev/mall-gateway:be2960005c1d3b3b1b39dc96ed2c1b3d2e586471-dev
          env:
            - name: NACOS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nacos-mall-prod-rw-user
                  key: username
            - name: NACOS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nacos-mall-prod-rw-user
                  key: password
            - name: NACOS_NAMESPACE
              valueFrom:
                secretKeyRef:
                  name: nacos-mall-prod-rw-user
                  key: namespace
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mall-gateway
spec:
  selector:
    app: mall-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
