apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-product
  template:
    metadata:
      labels:
        app: mall-product
    spec:
      containers:
        - name: mall-product
          image: lishuaidev/mall-product:05aeeb49a1cc0feae90be88df1720b8ec376e983-dev
          env:
            - name: NACOS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nacos-mall-prod-rw-user
                  key: username
            - name: NACOS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nacos-mall-prod-rw-user
                  key: password
            - name: NACOS_NAMESPACE
              valueFrom:
                secretKeyRef:
                  name: nacos-mall-prod-rw-user
                  key: namespace
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mall-mysql-rw-user
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mall-mysql-rw-user
                  key: password
                  # - name: JDK_JAVA_OPTIONS
                  #   value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=85.0 -Xms64M -XX:MaxMetaspaceSize=64M -Xss256k"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 10
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mall-product
spec:
  selector:
    app: mall-product
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
