apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/deploy.yaml
  - base/shuailli-cert.yaml
  - base/argocd-ingress.yaml

# patches:
#   - path: overlays/argocd-server-patch.yaml

namespace: argocd
