apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/cert-manager.yaml

patches:
  - path: overlays/namespace-patch.yaml
  - path: overlays/priority-class-patch.yaml
    target:
      kind: Deployment

namespace: infrastructure
