apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
        - name: nacos
          image: nacos/nacos-server:v2.5.1
          env:
            - name: MODE
              value: "standalone"
            # 鉴权
            - name: NACOS_AUTH_ENABLE
              value: "true"
            - name: NACOS_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: nacos-jwt-secret
                  key: token
            - name: NACOS_AUTH_IDENTITY_KEY
              value: "nacos_key"
            - name: NACOS_AUTH_IDENTITY_VALUE
              value: "nacos_value"
            # 资源占用压榨
            - name: JVM_XMS
              value: "256m"
            - name: JVM_XMX
              value: "600m"
            - name: JVM_XMN
              value: "128m"
          ports:
            - containerPort: 8848
              name: client
            - containerPort: 9848
              name: client-rpc
          resources:
            limits:
              memory: 640Mi
            requests:
              memory: 256Mi
          volumeMounts:
            - name: nacos-storage
              mountPath: /home/nacos/data
      volumes:
        - name: nacos-storage
          persistentVolumeClaim:
            claimName: nacos-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nacos-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/nacos"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nacos-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-service
spec:
  selector:
    app: nacos
  ports:
    - port: 8848
      name: server
      targetPort: 8848
    - port: 9848
      name: client-rpc
      targetPort: 9848
  clusterIP: None
