apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/cert-manager.yaml
  - base/tls-issuer.yaml

patches:
  - path: overlays/priority-class-patch.yaml
    target:
      kind: Deployment
