apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.13.0/deploy/static/provider/cloud/deploy.yaml

patches:
  - path: namespace-patch.yaml
  - path: security-waf-patch.yaml
    target:
      name: ingress-nginx-controller
  - path: security-ddos-patch.yaml
    target:
      name: ingress-nginx-controller

namespace: infrastructure
