apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/deploy.yaml

patches:
  - path: overlays/namespace-patch.yaml
  - path: overlays/service-patch.yaml
  - path: overlays/deploy-patch.yaml
  - path: overlays/security-patch.yaml

namespace: infrastructure
