apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
data:
  enable-modsecurity: "true"
  enable-owasp-core-rules: "true"
  modsecurity-snippet: |-
    SecRuleEngine On
    SecAuditEngine RelevantOnly
    SecAuditLog /var/log/nginx/modsec_audit.log

    # === SQL注入防护 ===
    Include /etc/nginx/owasp-modsecurity-crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
